<a href="https://colab.research.google.com/github/FintradeLab/CinC24_2/blob/main/03_Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a DS?**

A variable that stores a *value sequence*.

Expamples: List,arrays, tuplets, database

# **2. Linear Algebra**

## 2.1. Numpy

Numpy (Numerical Python) is a library that perform operations in DS. Meaning, it does linear algebra.

In [1]:
import numpy as np

## 2.2. Numpy arrays - Vectors and Matrices

In [2]:
# Column vector
a = np.array([[1],[2],[3]])
print(a)
print(a.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [3]:
# Row vector
b = np.array([[4,5,6]])
print(b)
print(b.shape)

[[4 5 6]]
(1, 3)


In [4]:
# Squared Matrix
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [5]:
s = A.shape
print(s)

n, m = A.shape
print('Number of rows', n)
print('Number of columns', m)

(3, 3)
Number of rows 3
Number of columns 3


In [6]:
## WARNING!!!
x = 2
y = np.array([[2]])
print(type(x), type(y))

<class 'int'> <class 'numpy.ndarray'>


## 2.3. Slicing

In [8]:
# Extract one element

print(A[0,0]) # Extract the element in row 1 column 1
print(a[1,0]) # Extract the element in row 2 column 1
print(b[0,1]) # Extract the element in row 1 column 2

1
2
5


In [9]:
# A little trick

print(A[-1,-1]) # Extract the last element

9


In [10]:
# Extract a subset
print(A[0:2, 1:3])

[[2 3]
 [5 6]]


In [11]:
# Extract the whole row
print(A[1,:])

[4 5 6]


In [12]:
# Extract the whole column
print(A[:,1])

[2 5 8]


# **3. Useful Methods**

## 3.1. Find

In [15]:
# Find a value
print(np.where(A == 5))

(array([1]), array([1]))


## 3.2. Zeros and Ones

In [16]:
# Zeros

z1 = np.zeros((2,3))
print(z1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [17]:
# Ones

o1 = np.ones((2,3))
print(o1)

[[1. 1. 1.]
 [1. 1. 1.]]


## 3.3. Full

In [20]:
# Create an object with the same value
print(np.full((2,3), 99))

[[99 99 99]
 [99 99 99]]


## 3.4. Arange

In [24]:
# Create a value squence

s1 = np.arange(start = 0, stop = 5.5, step = 0.5)
print(s1)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]
