<a href="https://colab.research.google.com/github/FintradeLab/CinC24_2/blob/main/03_Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a DS?**

A variable that stores a *value sequence*.

Expamples: List,arrays, tuplets, database

# **2. Linear Algebra**

## 2.1. Numpy

Numpy (Numerical Python) is a library that perform operations in DS. Meaning, it does linear algebra.

In [2]:
import numpy as np

## 2.2. Numpy arrays - Vectors and Matrices

In [3]:
# Column vector
a = np.array([[1],[2],[3]])
print(a)
print(a.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [4]:
# Row vector
b = np.array([[4,5,6]])
print(b)
print(b.shape)

[[4 5 6]]
(1, 3)


In [5]:
# Squared Matrix
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [6]:
s = A.shape
print(s)

n, m = A.shape
print('Number of rows', n)
print('Number of columns', m)

(3, 3)
Number of rows 3
Number of columns 3


In [7]:
## WARNING!!!
x = 2
y = np.array([[2]])
print(type(x), type(y))

<class 'int'> <class 'numpy.ndarray'>


## 2.3. Slicing

In [8]:
# Extract one element

print(A[0,0]) # Extract the element in row 1 column 1
print(a[1,0]) # Extract the element in row 2 column 1
print(b[0,1]) # Extract the element in row 1 column 2

1
2
5


In [9]:
# A little trick

print(A[-1,-1]) # Extract the last element

9


In [10]:
# Extract a subset
print(A[0:2, 1:3])

[[2 3]
 [5 6]]


In [11]:
# Extract the whole row
print(A[1,:])

[4 5 6]


In [12]:
# Extract the whole column
print(A[:,1])

[2 5 8]


# **3. Useful Methods**

## 3.1. Find

In [13]:
# Find a value
print(np.where(A == 5))

(array([1]), array([1]))


## 3.2. Zeros and Ones

In [14]:
# Zeros

z1 = np.zeros((2,3))
print(z1)

[[0. 0. 0.]
 [0. 0. 0.]]


In [15]:
# Ones

o1 = np.ones((2,3))
print(o1)

[[1. 1. 1.]
 [1. 1. 1.]]


## 3.3. Full

In [16]:
# Create an object with the same value
print(np.full((2,3), 99))

[[99 99 99]
 [99 99 99]]


## 3.4. Arange

In [17]:
# Create a value squence

s1 = np.arange(start = 0, stop = 5.5, step = 0.5)
print(s1)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5. ]


## 3.5. Linear space

In [20]:
np.linspace(start = 0, stop = 10, num = 7)

array([ 0.        ,  1.66666667,  3.33333333,  5.        ,  6.66666667,
        8.33333333, 10.        ])

# **4. Random numbers**

## 4.1. Uniform distribution [0,1)

In [26]:
# A random number
np.random.rand()

0.42157945978009104

In [32]:
# A matrix or vector
np.random.rand(2,3)

array([[0.58607567, 0.99737797, 0.19753541],
       [0.79345647, 0.198236  , 0.75963903]])

In [41]:
### Example 1 - Toin coss

if np.random.rand() > 0.5:
  print('Heads')
else:
  print('Tails')



Heads


In [55]:
### Example 2 - Three options

toss = np.random.rand()

if toss <= 0.7:
  print('Win')
elif toss > 0.7 and toss <= 0.8:
  print('Draw')
else:
  print('Lose')


Lose


In [65]:
# Exercise
## Simulate three coin tosses
## Present the result according to:

## 1. If the person get 3 Heads win 100k
## 2. If the person get 3 Tails lose 100k
## 3. In any other case, nothing happens

toss1 = np.random.rand()
toss2 = np.random.rand()
toss3 = np.random.rand()

if toss1 > 0.5 and toss2 > 0.5 and toss3 > 0.5:
  print('Win')
  print('You got 3 Heads')
elif toss1 < 0.5 and toss2 < 0.5 and toss3 < 0.5:
  print('Lose')
  print('You got 3 Tails')
else:
    print('Nothing')
    print('You got at least 1 Tails')

Nothing
You got at least 1 Tails


In [66]:
# Exercise
## Simulate three coin tosses
## Present the result according to:

## 1. If the person get 3 Heads win 100k
## 2. If the person get 3 Tails lose 100k
## 3. In any other case, nothing happens

toss = np.random.rand(3)

if np.all(toss >= 0.5):
  print('Win')
  print('You got 3 Heads')
elif np.all(toss < 0.5):
  print('Lose')
  print('You got 3 Tails')
else:
    print('Nothing')
    print('You got at least 1 Tails')

Nothing
You got at least 1 Tails


## 4.2. Uniform distribution [a,b)

In [82]:
# A random number
np.random.uniform(low = -1, high = 1)

0.14777569073456753

In [86]:
# A matrix or vector
np.random.uniform(low = -1, high = 1, size = (2,3))

array([[ 0.75711449,  0.81741447, -0.5141829 ],
       [-0.34775701,  0.9466548 , -0.26082622]])

## 4.3. Triangular distribution

In [98]:
np.random.triangular(left = 30, mode = 100, right = 170)

95.58232799041608