<a href="https://colab.research.google.com/github/FintradeLab/CinC24_2/blob/main/03_Data_Structure.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **1. What is a DS?**

A variable that stores a *value sequence*.

Expamples: List,arrays, tuplets, database

# **2. Linear Algebra**

## 2.1. Numpy

Numpy (Numerical Python) is a library that perform operations in DS. Meaning, it does linear algebra.

In [5]:
import numpy as np

## 2.2. Numpy arrays - Vectors and Matrices

In [11]:
# Column vector
a = np.array([[1],[2],[3]])
print(a)
print(a.shape)

[[1]
 [2]
 [3]]
(3, 1)


In [12]:
# Row vector
b = np.array([[4,5,6]])
print(b)
print(b.shape)

[[4 5 6]]
(1, 3)


In [13]:
# Squared Matrix
A = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])
print(A)
print(A.shape)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
(3, 3)


In [16]:
s = A.shape
print(s)

n, m = A.shape
print('Number of rows', n)
print('Number of columns', m)

(3, 3)
Number of rows 3
Number of columns 3


In [17]:
## WARNING!!!
x = 2
y = np.array([[2]])
print(type(x), type(y))

<class 'int'> <class 'numpy.ndarray'>
